openapi: 3.0.0
info:
  description: "Pygott & Crone API | https://pygott-crone.com/restful <br><br> <h2>Authentication</h2>Requests are authenticated using a hard-coded API key. The API key should be supplied as a header i.e. <code>Apikey: YOURAPIKEYHERE</code>"
  version: "1.0.0"
  title: Pygott & Crone API
  contact:
    email: webmasters@pygott-crone.com
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
tags:
  - name: Staff
    description: Staff Related Actions
  - name: Survey
    description: Survey Related Actions
  - name: Ledger
    description: Ledger Related Actions
  - name: Questionnaire
    description: Questionnaire Related Actions
  - name: Diary
    description: Diary Related Actions
paths:
  /staff:
    get:
      tags:
        - Staff
      summary: Get a list of staff
      operationId: staffList
      description: |
        Returns a list of all staff depending on query.
      parameters:
        - in: query
          name: hasReapit
          description: API Key
          required: false
          schema:
            type: boolean
        - in: query
          name: reapitId
          description: Reapit ID of the user to get specific data
          required: false
          schema:
            type: string
      responses:
        '200':
          description: Successfully returned list of user(s)
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  message:
                    type: string
                example: # Sample object
                  astuart@pygott-crone.com:
                    wpid: 23201
                    name: Adam Stuart
                    fullphoto: 'https://www.pygott-crone.com/wp-content/uploads/2020/01/Adam_Stuart.jpg'
                    email: astuart@pygott-crone.com
                    primary_branch: GAR
                    join_date: '2020-01-20T00:00:00+00:00'
                    service_length: '1 year, 6 months'
                    staff_id: AST
                    job_title: Sales Negotiator
                    telephone: 01529 414333
                    extension: '1402'
                    square_photo: 'https://www.pygott-crone.com/wp-content/uploads/2016/01/Adam_Stuart.jpg'
                  ajlil@pygott-crone.com:
                    wpid: 23
                    name: Ahmed Jlil
                    fullphoto: 'https://www.pygott-crone.com/wp-content/uploads/2016/01/ahmed-jlil-opt.jpg'
                    email: ajlil@pygott-crone.com
                    primary_branch: LIR
                    join_date: '2013-04-22T00:00:00+01:00'
                    service_length: '8 years, 2 months'
                    staff_id: AHJ
                    job_title: Financial Services Director
                    telephone: 01529 411083
                    extension: '1120'
                    square_photo: 'https://www.pygott-crone.com/wp-content/uploads/2016/01/ahmed-jlil-opt-1.jpg'
        '401':
          description: bad input parameter
  /survey:
    post:
      tags:
        - Survey
      summary: Send survey referral form
      operationId: surveySend
      description: |
        Send a survey referral form
      parameters:
        - in: query
          name: title
          description: title of the person e.g Mr, Mrs etc...
          required: false
          schema:
            type: string
        - in: query
          name: first_name
          description: First name of the person.
          required: true
          schema:
            type: string
        - in: query
          name: last_name
          description: Last name of the user
          required: true
          schema:
            type: string
        - in: query
          name: tel_number
          description: Contact number of the user
          required: true
          schema:
            type: string
        - in: query
          name: email
          description: Contact email of the user
          required: true
          schema:
            type: string
        - in: query
          name: postcode
          description: Postcode of the user
          required: true
          schema:
            type: string
        - in: query
          name: property_name_number
          description: Name or number of the property
          required: true
          schema:
            type: string
        - in: query
          name: estate_agent
          description: Name of the estate agent
          required: true
          schema:
            type: string
        - in: query
          name: other
          description: Other comments
          required: true
          schema:
            type: string
        - in: query
          name: survey_type
          description: Type of survey | homebuyer, building, valuation, snagging, unsure
          required: true
          schema:
            type: string
        - in: query
          name: staff
          description: The Reapit ID of the member of staff
          required: true
          schema:
            type: string
      responses: 
        '200':
          description: Successfully sent survey
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  result:
                    type: string
                example: # Sample object
                  success: true
        '400':
          description: bad input parameter
  /ledger:
    get:
      tags:
        - Ledger
      summary: Returns a list of Pygott & Crone performance data
      operationId: ledgerGet
      description: |
        Returns a list of Pygott & Crone performance data
      parameters:
        - in: query
          name: fromDate
          description: Request data from after this date
          required: false
          schema:
            type: string
        - in: query
          name: toDate
          description: Request data from before this date
          required: false
          schema:
            type: string
        - in: query
          name: ledgerTypes
          description: Only show records matching one of the supplied types
          required: false
          schema:
            type: integer
        - in: query
          name: returnFields
          description: Specify the fields required to be returned
          required: false
          schema:
            type: string
      responses: 
        '200':
          description: Successfully returned the ledger
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  result:
                    type: string
                example: # Sample object
                  success: true
                  array: items
        '400':
          description: bad input parameter
  /questionnaire:
    get:
      tags:
        - Questionnaire
      summary: Returns a list of Pygott & Crone performance data
      operationId: questionnaireGet
      description: |
        Returns a list questionnaires
      parameters:
        - in: query
          name: fromDate
          description: Request data from after this date
          required: true
          schema:
            type: string
        - in: query
          name: typename
          description: Type of questionnaire
          required: true
          schema:
            type: string
      responses: 
        '200':
          description: Successfully returned the list
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  result:
                    type: string
                example: # Sample object
                  success: true
                  array: items
        '400':
          description: bad input parameter
    post:
      tags:
        - Questionnaire
      summary: Create a questionnaires
      operationId: questionnairePost
      description: |
        Create a questionnaires
      parameters:
        - in: query
          name: typename
          description: Type of questionnaire
          required: true
          schema:
            type: string
        - in: query
          name: clientname
          description: Name of the client
          required: true
          schema:
            type: string
        - in: query
          name: advisername
          description: Name of the mortgage & protection adviser
          required: true
          schema:
            type: string
        - in: query
          name: staffname
          description: Name of the user creating the request
          required: true
          schema:
            type: string
        - in: query
          name: staffid
          description: WP ID of the user
          required: true
          schema:
            type: string
      responses: 
        '200':
          description: Successfully created the questionnaire
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  result:
                    type: string
                example: # Sample object
                  success: true
                  array: items
        '400':
          description: bad input parameter
    delete:
      tags:
        - Questionnaire
      summary: Delete a questionnaires
      operationId: questionnaireDelete
      description: |
        Delete a questionnaires
      parameters:
        - in: query
          name: typename
          description: Type of questionnaire
          required: true
          schema:
            type: string
        - in: query
          name: recordId
          description: The id of the questionnaire
          required: true
          schema:
            type: string
        - in: query
          name: hash
          description: The hash of the questionnaire
          required: true
          schema:
            type: string
      responses: 
        '200':
          description: Successfully deleted the questionnaire
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  result:
                    type: string
                example: # Sample object
                  success: true
                  array: items
        '400':
          description: bad input parameter
  /diary:
    get:
      tags:
        - Diary
      summary: Returns a list of property-related appointments for the supplied staff member
      operationId: diaryGet
      description: |
        Returns a list of property-related appointments for the supplied staff member
      parameters:
        - in: query
          name: staffID
          description: The 2 or 3 character staff id
          required: true
          schema:
            type: string
        - in: query
          name: fromDate
          description: Only show records from this date (defaults to the start of the previous month)
          required: false
          schema:
            type: string
        - in: query
          name: toDate
          description: Only show records up to this date (defaults to current datetime)
          required: false
          schema:
            type: string
      responses: 
        '200':
          description: Successfully returned the ledger
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  result:
                    type: string
                example: # Sample object
                  success: true
                  array: items
        '400':
          description: bad input parameter
